version: '3.7'

# !Only for dev/test purpose!

services:

  app:
    build:
      dockerfile: ./Dockerfile-nginx
      context: ./
    #      args:
    #        - NPM_TOKEN=${NPM_TOKEN}
    depends_on:
      - db
#        condition: service_healthy
    ports:
      - '127.0.0.1:8800:80'
      - '127.0.0.1:6001:6001'
    volumes:
      - ./:/var/www/app/
    restart: always
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: collabquest
      DB_USERNAME: root
      DB_PASSWORD: test12345
    command: sh ./wait-for-mysql.sh /var/www/app/start.sh
    #    command: ./wait-for-it.sh db:3306 -- sh start.sh


  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test12345
      MYSQL_DATABASE: collabquest
    ports:
      - '127.0.0.1:3307:3306'
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

#  solr:
#    image: solr:8
#    ports:
#      - "127.0.0.1:8983:8983"
#    restart: always
#    volumes:
#      - data:/var/solr
#    entrypoint:
#      - solr-precreate
#      - gettingstarted
volumes:
  db:
  data:
#
#secrets:
#  db_password:
#    file: ./config/secrets/postgres_password.txt
