version: '3.7'

# !Only for dev/test purpose!

services:

  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    #      args:
    #        - NPM_TOKEN=${NPM_TOKEN}
    depends_on:
      - db
#        condition: service_healthy
    ports:
      - '127.0.0.1:8801:80'
      - '127.0.0.1:6002:6001'
    volumes:
      - ./storage/logs:/var/www/app/storage/logs
#      - ./vendor:/var/www/app/vendor
    restart: always
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: collabquest
      DB_USERNAME: root
      DB_PASSWORD: test12345
    command: sh ./wait-for-mysql.sh /var/www/app/start.sh
    #    command: ./wait-for-it.sh db:3306 -- sh start.sh


  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test12345
      MYSQL_DATABASE: collabquest
    ports:
      - '127.0.0.1:3308:3306'
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10

volumes:
  db:
#
#secrets:
#  db_password:
#    file: ./config/secrets/postgres_password.txt
